# Purpose: Generate combined executive summary stats and visuals (GA + Shinyapps)

source("R/00-setup.R")

# Read the data generated by 02-analyze-usage.R and 03-analyze-concurrency.R
weekly_usage <- read_csv(file.path(OUTPUT_TABLES, "weekly_usage.csv"))
concurrency_summary <- read_csv(file.path(
  OUTPUT_TABLES,
  "concurrency_summary.csv"
))


# 1. Trend line of app visits (sessions)
# Combined plot
visits_trend_plot <- weekly_usage |>
  ggplot(aes(x = week, y = total_sessions, color = pageTitle)) +
  geom_line(linewidth = 1.5) +
  labs(
    title = "Weekly App Visits Trend",
    x = "Week",
    y = "Total Visits (Sessions)",
    color = "App"
  ) +
  theme_minimal(base_size = 16) +
  theme(
    plot.title = element_text(size = 22, face = "bold"),
    axis.title = element_text(size = 18),
    axis.text = element_text(size = 14),
    legend.title = element_text(size = 18),
    legend.text = element_text(size = 14)
  )

# Faceted plot (one per app)
visits_trend_faceted_plot <- weekly_usage |>
  ggplot(aes(x = week, y = total_sessions, color = pageTitle)) +
  geom_line(linewidth = 1.5, show.legend = FALSE) +
  facet_wrap(~pageTitle, scales = "free_y") +
  labs(
    title = "Weekly App Visits Trend (By App)",
    x = "Week",
    y = "Total Visits (Sessions)"
  ) +
  theme_minimal(base_size = 16) +
  theme(
    plot.title = element_text(size = 22, face = "bold"),
    axis.title = element_text(size = 18),
    axis.text.x = element_text(angle = 45, hjust = 1, size = 12),
    axis.text.y = element_text(size = 12),
    strip.text = element_text(size = 14, face = "bold")
  )


# 2. Min/Max weekly visits summary table
visits_minmax_summary <- weekly_usage |>
  summarize(
    min_weekly_visits = min(total_sessions, na.rm = TRUE),
    median_weekly_visits = median(total_sessions, na.rm = TRUE),
    avg_weekly_visits = round(mean(total_sessions, na.rm = TRUE), 1),
    max_weekly_visits = max(total_sessions, na.rm = TRUE),
    .by = pageTitle
  ) |>
  arrange(desc(max_weekly_visits))


# Plot the Min/Max range, boxplot of weekly visits per app
visits_minmax_plot <- weekly_usage |>
  mutate(
    pageTitle = fct_reorder(pageTitle, total_sessions, .fun = max, na.rm = TRUE)
  ) |>
  ggplot(aes(x = pageTitle, y = total_sessions, fill = pageTitle)) +
  geom_boxplot(
    alpha = 0.7,
    outlier.size = 3,
    show.legend = FALSE
  ) +
  labs(
    title = "Distribution of Weekly Visits per App",
    subtitle = "Box shows 25th to 75th percentile, line is median, dots are outliers",
    x = "App",
    y = "Weekly Visits (Sessions)"
  ) +
  theme_minimal(base_size = 16) +
  theme(
    plot.title = element_text(size = 22, face = "bold"),
    plot.subtitle = element_text(size = 16),
    axis.title = element_text(size = 18),
    axis.text.x = element_text(angle = 45, hjust = 1, size = 14),
    axis.text.y = element_text(size = 14)
  )

# Boxplot for high-traffic apps only
high_traffic_apps <- c("popApp", "Student Outcomes")

visits_minmax_plot_high <- weekly_usage |>
  filter(pageTitle %in% high_traffic_apps) |>
  mutate(
    pageTitle = fct_reorder(pageTitle, total_sessions, .fun = max, na.rm = TRUE)
  ) |>
  ggplot(aes(x = pageTitle, y = total_sessions, fill = pageTitle)) +
  geom_boxplot(
    alpha = 0.7,
    outlier.size = 3,
    show.legend = FALSE
  ) +
  labs(
    title = "Distribution of Weekly Visits (High Traffic Apps)",
    subtitle = "Box shows 25th to 75th percentile, line is median, dots are outliers",
    x = "App",
    y = "Weekly Visits (Sessions)"
  ) +
  theme_minimal(base_size = 16) +
  theme(
    plot.title = element_text(size = 22, face = "bold"),
    plot.subtitle = element_text(size = 16),
    axis.title = element_text(size = 18),
    axis.text.x = element_text(angle = 45, hjust = 1, size = 14),
    axis.text.y = element_text(size = 14)
  )

# Boxplot for lower-traffic apps only
visits_minmax_plot_low <- weekly_usage |>
  filter(!pageTitle %in% high_traffic_apps) |>
  mutate(
    pageTitle = fct_reorder(pageTitle, total_sessions, .fun = max, na.rm = TRUE)
  ) |>
  ggplot(aes(x = pageTitle, y = total_sessions, fill = pageTitle)) +
  geom_boxplot(
    alpha = 0.7,
    outlier.size = 3,
    show.legend = FALSE
  ) +
  coord_cartesian(
    ylim = c(
      0,
      quantile(
        weekly_usage |>
          filter(!pageTitle %in% high_traffic_apps) |>
          pull(total_sessions),
        0.95,
        na.rm = TRUE
      )
    )
  ) +
  labs(
    title = "Distribution of Weekly Visits (Low Traffic Apps)",
    subtitle = "Box shows 25th to 75th percentile, line is median, dots are outliers (Y-axis zoomed)",
    x = "App",
    y = "Weekly Visits (Sessions)"
  ) +
  theme_minimal(base_size = 16) +
  theme(
    plot.title = element_text(size = 22, face = "bold"),
    plot.subtitle = element_text(size = 16),
    axis.title = element_text(size = 18),
    axis.text.x = element_text(angle = 45, hjust = 1, size = 14),
    axis.text.y = element_text(size = 14)
  )


# 3. Max concurrent visits plot
max_concurrent_plot <- concurrency_summary |>
  filter(interval == "1m") |> # Use 1-minute buckets for true peak
  mutate(app_name = fct_reorder(app_name, max_concurrent, .desc = TRUE)) |>
  ggplot(aes(x = app_name, y = max_concurrent, fill = app_name)) +
  geom_col(show.legend = FALSE) +
  geom_text(aes(label = max_concurrent), vjust = -0.5, size = 5) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.1))) + # Add space for labels
  labs(
    title = "Maximum Concurrent Visits by App",
    subtitle = "Based on 1-minute interval peaks",
    x = "App",
    y = "Max Concurrent Users"
  ) +
  theme_minimal(base_size = 16) +
  theme(
    plot.title = element_text(size = 22, face = "bold"),
    plot.subtitle = element_text(size = 16),
    axis.title = element_text(size = 18),
    axis.text.x = element_text(angle = 45, hjust = 1, size = 14),
    axis.text.y = element_text(size = 14)
  )


# --- SAVE OUTPUTS ---

# Save the summary table
write_csv(
  visits_minmax_summary,
  file.path(OUTPUT_TABLES, "visits_minmax_summary.csv")
)

# Save the plots
ggsave(
  file.path(OUTPUT_VISUALS, "visits_trend_plot.png"),
  visits_trend_plot,
  width = 10,
  height = 6
)
ggsave(
  file.path(OUTPUT_VISUALS, "visits_trend_faceted_plot.png"),
  visits_trend_faceted_plot,
  width = 12,
  height = 8
)
ggsave(
  file.path(OUTPUT_VISUALS, "visits_minmax_plot.png"),
  visits_minmax_plot,
  width = 10,
  height = 6
)
ggsave(
  file.path(OUTPUT_VISUALS, "visits_minmax_plot_high.png"),
  visits_minmax_plot_high,
  width = 8,
  height = 6
)
ggsave(
  file.path(OUTPUT_VISUALS, "visits_minmax_plot_low.png"),
  visits_minmax_plot_low,
  width = 10,
  height = 6
)
ggsave(
  file.path(OUTPUT_VISUALS, "max_concurrent_plot.png"),
  max_concurrent_plot,
  width = 10,
  height = 6
)

message("Executive summary visuals and tables saved to outputs/")
